# Generated by Django 4.2.5 on 2023-10-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='ihdjfb.jpg', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
