# Generated by Django 4.2.5 on 2023-10-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
